### ISSUE TITLE
The `save-state` command is depricated and will be disabled soon

### ISSUE THREAD

**Issue by hanjoosten** [freckle/stack-cache-action#132]
I get the following warnings when I use stack-cache-action:

![image](https://user-images.githubusercontent.com/1159672/210640500-93bf68c4-6c8f-4e2c-acc6-2000c27aa893.png)

Here is the log:

https://github.com/AmpersandTarski/Ampersand/actions/runs/3839988068/jobs/6538490545#step:3:9

**Comment by alexkalderimis** [comment]
The announcement: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The key section is the June dealine:

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

**Comment by alexkalderimis** [comment]
Oddly, the advice is to upgrade the `@actions/core package` to v1.10.0, but that is already the version in the `yaml.lock` file.

**Comment by hanjoosten** [comment]
Hi @alexkalderimis , I don't know exactly what is going on here, but the blog suggests that the new `GITHUB_STATE` and `GITHUB_OUTPUT` environment files should be written. I think that means a change in your code?

**Comment by pbrisbin** [comment]
@hanjoosten We don't directly emit the old `echo "::save-state"` kind of commands, which is what you are supposed to transition to the `GITHUB_X` env vars. We call `@actions/core`, which implements `saveState()`, which needed to be updated. As @alexkalderimis mentioned, that happened in v1.10.0, [which we are using](https://github.com/freckle/stack-cache-action/blob/main/yarn.lock#L22). So I too am completely confused why we see still this warning.

**Comment by pbrisbin** [comment]
Ah, it looks like the `save/index.js` file is not updated. It was last touched on 6/7/2022 and the `@actions/core` update landed on 10/13/2022. Unclear how that happened, since `restore/index.js` was touched on 10/17/2022 just fine.

At least that's something I can investigate and fix!

**Comment by pbrisbin** [comment]
OK, I rebuilt the `dist/` files and [the warning seems gone](https://github.com/freckle/stack-cache-action/actions/runs/4296549620). I updated `@v2` and released `v2.0.9`. No idea how this happened, but I think we're good now.
