### ISSUE TITLE
Link to https://tech.freckle.com/2021/05/18/haskell-on-actions/ in README

### ISSUE THREAD

**Issue by andreasabel** [freckle/stack-cache-action#61]
I came by this project via a Google search on how to cache correctly in stack CIs.  After browsing the repo, I wondered where to find more evidence that (and how) this works.

It would be great if you could link to some real-world CI scripts that use this action.

Already linking to https://tech.freckle.com/2021/05/18/haskell-on-actions/ (which found by more googling) from the README would be helpful.

**Comment by pbrisbin** [comment]
Hi there! I'm always happen to add more context in our READMEs, but I'm not exactly sure what you're after. Could you maybe make a PR that adds something along the lines of what you're thinking?

**Comment by andreasabel** [comment]
Thanks for the quick response! See 
- https://github.com/freckle/stack-cache-action/pull/62
